/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panels;

import access.ClienteDAO;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.ClienteModel;
import persistencia.ArchiCliente;
import view.Login;
import view.Principal;

/**
 *
 * @author nabet
 */
public class panel_user extends javax.swing.JPanel {

    /**
     * Creates new form panel_user
     *
     * @throws java.io.IOException
     * @throws java.lang.ClassNotFoundException
     */
    public panel_user() throws IOException, ClassNotFoundException {
        initComponents();
        ClienteModel clienteModel = recuperar();
        ClienteDAO clienteDao = new ClienteDAO();
        ArrayList<ClienteModel> cliente = clienteDao.datosCliente(clienteModel.getUsername());
        txt_username.setText(cliente.get(0).getUsername());
        txt_email.setText(cliente.get(0).getEmail());
        txt_cel.setText(cliente.get(0).getCelular());
        txt_name.setText(cliente.get(0).getNombre());
        txt_lastName.setText(cliente.get(0).getApellido());
        txt_dateBorn.setText(cliente.get(0).getNacimiento());
        email_field.setText(cliente.get(0).getEmail());
        cel_field.setText(cliente.get(0).getCelular());
        name_field.setText(cliente.get(0).getNombre());
        lastName_field.setText(cliente.get(0).getApellido());
    }

    public static ClienteModel recuperar() throws IOException, ClassNotFoundException {
        ArchiCliente rec = new ArchiCliente();
        ClienteModel recuperar = rec.recuperar();
        return recuperar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        email_field = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        cel_field = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        name_field = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        lastName_field = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        btn_register = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        txt_username = new javax.swing.JLabel();
        txt_email = new javax.swing.JLabel();
        txt_cel = new javax.swing.JLabel();
        txt_name = new javax.swing.JLabel();
        txt_lastName = new javax.swing.JLabel();
        txt_dateBorn = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));
        setPreferredSize(new java.awt.Dimension(690, 540));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Editar Perfil");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 240, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Perfil");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 240, -1));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("USERNAME:");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("CORREO ELECTRONICO:");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("CELULAR:");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("NOMBRE:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("FECHA DE NACIMIENTO:");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("APELLIDO:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        email_field.setBackground(new java.awt.Color(51, 51, 51));
        email_field.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        email_field.setForeground(new java.awt.Color(255, 255, 255));
        email_field.setText("Ingrese Nuevo Correo");
        email_field.setBorder(null);
        email_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                email_fieldFocusGained(evt);
            }
        });
        email_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_fieldActionPerformed(evt);
            }
        });
        add(email_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 140, -1));

        jSeparator8.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));
        add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 160, 10));

        cel_field.setBackground(new java.awt.Color(51, 51, 51));
        cel_field.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cel_field.setForeground(new java.awt.Color(255, 255, 255));
        cel_field.setText("Ingresae Nuevo Celular");
        cel_field.setBorder(null);
        cel_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cel_fieldFocusGained(evt);
            }
        });
        cel_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cel_fieldActionPerformed(evt);
            }
        });
        add(cel_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 160, -1));

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 160, 10));

        name_field.setBackground(new java.awt.Color(51, 51, 51));
        name_field.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        name_field.setForeground(new java.awt.Color(255, 255, 255));
        name_field.setText("Ingrese Nuevo Nombre");
        name_field.setBorder(null);
        name_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                name_fieldFocusGained(evt);
            }
        });
        name_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_fieldActionPerformed(evt);
            }
        });
        add(name_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 160, -1));

        jSeparator5.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, 160, 10));

        lastName_field.setBackground(new java.awt.Color(51, 51, 51));
        lastName_field.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lastName_field.setForeground(new java.awt.Color(255, 255, 255));
        lastName_field.setText("Ingrese Nuevo Apellido");
        lastName_field.setBorder(null);
        lastName_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lastName_fieldFocusGained(evt);
            }
        });
        lastName_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastName_fieldActionPerformed(evt);
            }
        });
        add(lastName_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, 160, -1));

        jSeparator6.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, 160, 10));

        btn_register.setBackground(new java.awt.Color(60, 226, 124));
        btn_register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_registerMouseClicked(evt);
            }
        });
        btn_register.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Editar Perfil");
        btn_register.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, -1));

        add(btn_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 440, 110, 40));

        txt_username.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txt_username.setForeground(new java.awt.Color(255, 255, 255));
        txt_username.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txt_username.setText("admin");
        add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        txt_email.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txt_email.setForeground(new java.awt.Color(255, 255, 255));
        txt_email.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txt_email.setText("admin@gmail.com");
        add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        txt_cel.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txt_cel.setForeground(new java.awt.Color(255, 255, 255));
        txt_cel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txt_cel.setText("3005678990");
        add(txt_cel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        txt_name.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txt_name.setForeground(new java.awt.Color(255, 255, 255));
        txt_name.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txt_name.setText("Admin");
        add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, -1, -1));

        txt_lastName.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txt_lastName.setForeground(new java.awt.Color(255, 255, 255));
        txt_lastName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txt_lastName.setText("Rules");
        add(txt_lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, -1, -1));

        txt_dateBorn.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txt_dateBorn.setForeground(new java.awt.Color(255, 255, 255));
        txt_dateBorn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txt_dateBorn.setText("2003-2-25");
        add(txt_dateBorn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void email_fieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_email_fieldFocusGained
        // TODO add your handling code here:
        email_field.setText("");
    }//GEN-LAST:event_email_fieldFocusGained

    private void email_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_fieldActionPerformed

    private void cel_fieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cel_fieldFocusGained
        // TODO add your handling code here:
        cel_field.setText("");
    }//GEN-LAST:event_cel_fieldFocusGained

    private void cel_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cel_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cel_fieldActionPerformed

    private void name_fieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_name_fieldFocusGained
        // TODO add your handling code here:
        name_field.setText("");
    }//GEN-LAST:event_name_fieldFocusGained

    private void name_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_fieldActionPerformed

    private void lastName_fieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastName_fieldFocusGained
        // TODO add your handling code here:
        lastName_field.setText("");
    }//GEN-LAST:event_lastName_fieldFocusGained

    private void lastName_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastName_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastName_fieldActionPerformed

    private void btn_registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registerMouseClicked
        // TODO add your handling code here:
        ClienteDAO clienteDao = new ClienteDAO();
        ClienteModel clienteModel = new ClienteModel(txt_username.getText(), name_field.getText(), lastName_field.getText(), email_field.getText(),
                cel_field.getText(), txt_dateBorn.getText());
        String actualizado = clienteDao.actualizarCliente(clienteModel);

        if (actualizado != null) {
            JOptionPane.showMessageDialog(this, actualizado);
        } else {
            JOptionPane.showMessageDialog(this, actualizado);
        }
    }//GEN-LAST:event_btn_registerMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_register;
    private javax.swing.JTextField cel_field;
    private javax.swing.JTextField email_field;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField lastName_field;
    private javax.swing.JTextField name_field;
    private javax.swing.JLabel txt_cel;
    private javax.swing.JLabel txt_dateBorn;
    private javax.swing.JLabel txt_email;
    private javax.swing.JLabel txt_lastName;
    private javax.swing.JLabel txt_name;
    private javax.swing.JLabel txt_username;
    // End of variables declaration//GEN-END:variables
}
