/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panels;

import access.BusquedaDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.CancionModel;
import model.PodcastModel;

/**
 *
 * @author nabet
 */
public class panel_search extends javax.swing.JPanel {

    /**
     * Creates new form panel_search
     */
    public panel_search() {
        initComponents();
    }

    public void mostrarResultadoCancion() {

        BusquedaDAO busqueda = new BusquedaDAO();

        change_resenia.setText("RESEÑA:");
        change_anio.setText("AÑO:");
        change_cantante.setText("CANTANTE:");

        ArrayList<CancionModel> cancion = busqueda.buscarCancion(search_field.getText());

        if (cancion.get(0).getTitulo().equals("No se encontro")) {
            JOptionPane.showMessageDialog(this, "No se encontro la cancion con titulo: " + search_field.getText());
        } else {

            txt_titulo.setText(cancion.get(0).getTitulo());
            txt_resenia.setText("<html> " + cancion.get(0).getResenia() + " <html>");
            txt_anio.setText(String.valueOf(cancion.get(0).getAnio()));
            txt_cantante.setText(cancion.get(0).getCantante());
        }
    }

    public void mostrarResultadoPodcast() {

        BusquedaDAO busqueda = new BusquedaDAO();

        change_resenia.setText("EPISODIOS:");
        change_anio.setText("TEMPORADAS:");
        change_cantante.setText("");

        ArrayList<PodcastModel> podcast = busqueda.buscarPodcast(search_field.getText());

        if (podcast.get(0).getTitulo().equals("No se encontro")) {
            JOptionPane.showMessageDialog(this, "No se encontro el podcast con titulo: " + search_field.getText());
        } else {

            txt_titulo.setText(podcast.get(0).getTitulo());
            txt_resenia.setText(String.valueOf(podcast.get(0).getEpisodios()));
            txt_anio.setText(String.valueOf(podcast.get(0).getTemporadas()));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbo_search = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        search_field = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        change_resenia = new javax.swing.JLabel();
        change_anio = new javax.swing.JLabel();
        change_cantante = new javax.swing.JLabel();
        txt_resenia = new javax.swing.JLabel();
        txt_anio = new javax.swing.JLabel();
        txt_cantante = new javax.swing.JLabel();
        txt_titulo = new javax.swing.JLabel();
        btn_search = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));
        setMinimumSize(new java.awt.Dimension(690, 540));
        setPreferredSize(new java.awt.Dimension(690, 540));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbo_search.setBackground(new java.awt.Color(51, 51, 51));
        cbo_search.setForeground(new java.awt.Color(255, 255, 255));
        cbo_search.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo de busqueda", "Canción", "Podcast" }));
        cbo_search.setBorder(null);
        cbo_search.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cbo_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_searchActionPerformed(evt);
            }
        });
        add(cbo_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 140, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Buscar");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 90, -1));

        search_field.setBackground(new java.awt.Color(51, 51, 51));
        search_field.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        search_field.setForeground(new java.awt.Color(255, 255, 255));
        search_field.setText("Ingrese dato a buscar");
        search_field.setBorder(null);
        search_field.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                search_fieldMouseClicked(evt);
            }
        });
        search_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_fieldActionPerformed(evt);
            }
        });
        add(search_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 310, -1));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 380, 10));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("TITULO:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        change_resenia.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        change_resenia.setForeground(new java.awt.Color(255, 255, 255));
        change_resenia.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        change_resenia.setText("RESEÑA:");
        add(change_resenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        change_anio.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        change_anio.setForeground(new java.awt.Color(255, 255, 255));
        change_anio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        change_anio.setText("AÑO:");
        add(change_anio, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        change_cantante.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        change_cantante.setForeground(new java.awt.Color(255, 255, 255));
        change_cantante.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        change_cantante.setText("CANTANTE:");
        add(change_cantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, -1, -1));

        txt_resenia.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txt_resenia.setForeground(new java.awt.Color(255, 255, 255));
        txt_resenia.setPreferredSize(new java.awt.Dimension(520, 60));
        txt_resenia.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        add(txt_resenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 440, 90));

        txt_anio.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txt_anio.setForeground(new java.awt.Color(255, 255, 255));
        txt_anio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        add(txt_anio, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, -1, 20));

        txt_cantante.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txt_cantante.setForeground(new java.awt.Color(255, 255, 255));
        txt_cantante.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        add(txt_cantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, -1, 20));

        txt_titulo.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txt_titulo.setForeground(new java.awt.Color(255, 255, 255));
        txt_titulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        add(txt_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, 20));

        btn_search.setBackground(new java.awt.Color(60, 226, 124));
        btn_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_searchMouseClicked(evt);
            }
        });
        btn_search.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Buscar");
        btn_search.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, -1));

        add(btn_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, 80, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void search_fieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_fieldMouseClicked
        // TODO add your handling code here:
        search_field.setText("");
    }//GEN-LAST:event_search_fieldMouseClicked

    private void search_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_fieldActionPerformed

    private void cbo_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_searchActionPerformed
        // TODO add your handling code here: 
        String searchType = cbo_search.getSelectedItem().toString();

        txt_titulo.setText("");
        txt_resenia.setText("");
        txt_anio.setText("");
        txt_cantante.setText("");

        switch (searchType) {
            case "Canción":
                change_resenia.setText("RESEÑA:");
                change_anio.setText("AÑO:");
                change_cantante.setText("CANTANTE:");
                break;
            case "Podcast":
                change_resenia.setText("EPISODIOS:");
                change_anio.setText("TEMPORADAS:");
                change_cantante.setText("");
                break;
            default:
                break;
        }
    }//GEN-LAST:event_cbo_searchActionPerformed

    private void btn_searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchMouseClicked
        // TODO add your handling code here:
        String searchType = cbo_search.getSelectedItem().toString();

        switch (searchType) {
            case "Canción":
                mostrarResultadoCancion();
                break;
            case "Podcast":
                mostrarResultadoPodcast();
                break;
            default:
                JOptionPane.showMessageDialog(this, "Seleccione tipo de busqueda");
                break;
        }
    }//GEN-LAST:event_btn_searchMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_search;
    private javax.swing.JComboBox<String> cbo_search;
    private javax.swing.JLabel change_anio;
    private javax.swing.JLabel change_cantante;
    private javax.swing.JLabel change_resenia;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField search_field;
    private javax.swing.JLabel txt_anio;
    private javax.swing.JLabel txt_cantante;
    private javax.swing.JLabel txt_resenia;
    private javax.swing.JLabel txt_titulo;
    // End of variables declaration//GEN-END:variables
}
