/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panels;

import access.ServicioDAO;
import access.TransmisionDAO;
import java.io.IOException;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ClienteModel;
import model.ServicioModel;
import persistencia.ArchiCliente;

/**
 *
 * @author nabet
 */
public class panel_agregar extends javax.swing.JPanel {

    /**
     * Creates new form panel_agregar
     *
     * @throws java.io.IOException
     * @throws java.lang.ClassNotFoundException
     */
    public panel_agregar() throws IOException, ClassNotFoundException {
        initComponents();
        mostrarDatos();
    }

    int seleccionado;
    String tituloSeleccionado;
    ClienteModel clienteModel = recuperar();
    String user = clienteModel.getUsername();

    private void mostrarDatos() {

        ServicioDAO listar = new ServicioDAO();

        DefaultTableModel table = new DefaultTableModel();
        table.addColumn("Titulo");
        agregar_table.setModel(table);

        ArrayList<ServicioModel> servicios = listar.listarDatos();

        String[] datos = new String[1];

        //Pasa los datos del ArrayList a un String[] y los lista en la tabla
        for (int i = 0; i < servicios.size(); i++) {
            datos[0] = servicios.get(i).getTitulo();
            table.addRow(datos);
        }
    }

    public static ClienteModel recuperar() throws IOException, ClassNotFoundException {
        //Recupera el username del cliente
        ArchiCliente rec = new ArchiCliente();
        ClienteModel recuperar = rec.recuperar();
        return recuperar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        agregar_table = new javax.swing.JTable();
        btn_agregar = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Agregar a escuchadas recientemente");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        agregar_table.setBackground(new java.awt.Color(51, 51, 51));
        agregar_table.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        agregar_table.setForeground(new java.awt.Color(255, 255, 255));
        agregar_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        agregar_table.setOpaque(false);
        agregar_table.setRowHeight(20);
        agregar_table.setRowMargin(0);
        agregar_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregar_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(agregar_table);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 590, 360));

        btn_agregar.setBackground(new java.awt.Color(60, 226, 124));
        btn_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_agregarMouseClicked(evt);
            }
        });
        btn_agregar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Agregar");
        btn_agregar.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, -1));

        add(btn_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 450, 80, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void agregar_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregar_tableMouseClicked

        //Obtiene el titulo de la fila seleccionada en la tabla
        seleccionado = agregar_table.rowAtPoint(evt.getPoint());
        tituloSeleccionado = String.valueOf(agregar_table.getValueAt(seleccionado, 0));
    }//GEN-LAST:event_agregar_tableMouseClicked

    private void btn_agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregarMouseClicked
        
        
        ServicioDAO obtenerId = new ServicioDAO();
        TransmisionDAO agregar = new TransmisionDAO();
        LocalDate date = LocalDate.now(); //Obtiene la fecha actual
        LocalTime hora = LocalTime.now(); // obtiene la hora actual
        String fecha = date.toString() + " " + hora.toString(); // concatena fecha y hora y los convierte en String 

        int id = obtenerId.obtenerIdServicio(tituloSeleccionado);

        agregar.agregar(user, id, fecha);

        JOptionPane.showMessageDialog(this, "Se agrego con exito " + tituloSeleccionado + " a escuchados recientemente");

    }//GEN-LAST:event_btn_agregarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable agregar_table;
    private javax.swing.JPanel btn_agregar;
    private javax.swing.JTextField email_field;
    private javax.swing.JTextField email_field1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
