/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panels;

import access.ServicioDAO;
import access.TransmisionDAO;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ClienteModel;
import model.TransmisionModel;
import persistencia.ArchiCliente;

/**
 *
 * @author nabet
 */
public class panel_home extends javax.swing.JPanel {

    /**
     * Creates new form panel_home
     *
     * @throws java.io.IOException
     * @throws java.lang.ClassNotFoundException
     */
    public panel_home() throws IOException, ClassNotFoundException {
        initComponents();
        mostrarDatos();
    }

    int seleccionado;
    String tituloSeleccionado;
    ClienteModel clienteModel = recuperar();
    String user = clienteModel.getUsername();

    private void mostrarDatos() {

        TransmisionDAO listar = new TransmisionDAO();

        DefaultTableModel table = new DefaultTableModel();
        table.addColumn("Titulo");
        table.addColumn("Fecha");
        historial_table.setModel(table);

        ArrayList<TransmisionModel> servicios = listar.listarDatos(user);

        String[] datos = new String[2];

        for (int i = 0; i < servicios.size(); i++) {
            datos[0] = servicios.get(i).getServicio();
            datos[1] = servicios.get(i).getFecha();
            table.addRow(datos);
        }

    }

    public static ClienteModel recuperar() throws IOException, ClassNotFoundException {
        ArchiCliente rec = new ArchiCliente();
        ClienteModel recuperar = rec.recuperar();
        return recuperar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        historial_table = new javax.swing.JTable();
        btn_delete = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));
        setPreferredSize(new java.awt.Dimension(690, 540));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Historial de reprodución");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        historial_table.setBackground(new java.awt.Color(51, 51, 51));
        historial_table.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        historial_table.setForeground(new java.awt.Color(255, 255, 255));
        historial_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        historial_table.setOpaque(false);
        historial_table.setRowHeight(20);
        historial_table.setRowMargin(0);
        historial_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                historial_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(historial_table);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 590, 360));

        btn_delete.setBackground(new java.awt.Color(255, 0, 51));
        btn_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_deleteMouseClicked(evt);
            }
        });
        btn_delete.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Eliminar del historial");
        btn_delete.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, -1));

        add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 450, 160, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void historial_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historial_tableMouseClicked
        // TODO add your handling code here:
        seleccionado = historial_table.rowAtPoint(evt.getPoint());
        tituloSeleccionado = String.valueOf(historial_table.getValueAt(seleccionado, 0));
    }//GEN-LAST:event_historial_tableMouseClicked

    private void btn_deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_deleteMouseClicked
        // TODO add your handling code here:
        ServicioDAO obtenerId = new ServicioDAO();
        TransmisionDAO eliminar = new TransmisionDAO();
        
        int id = obtenerId.obtenerIdServicio(tituloSeleccionado);

        eliminar.eliminar(user, id);

        JOptionPane.showMessageDialog(this, "Se elimino con exito " + tituloSeleccionado + " del historial");
    }//GEN-LAST:event_btn_deleteMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_delete;
    private javax.swing.JTable historial_table;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
